
<div class="left-box">
    
    <div class ="container">
        <div class ="home-image"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/US-carriers-1941-42.jpg/550px-US-carriers-1941-42.jpg"></div>
        <div class = "image-info">Welcome to Our WWII air Campaign site. We follow the airforce on Many different missions throughout the war.</div>
        
        <div class = "home-info">
			<div>
            <h3>The second Schweinfurt raid</h3>
            <p> The second Schweinfurt raid was a World War II air battle that took place October 14, 1943, over Nazi Germany between forces of the United States 8th Air Force and German Luftwaffe's fighter arm (Jagdwaffe). The aim of the American-led mission was a strategic bombing raid on ball bearing factories in order to reduce production of these vital parts for all manner of war machines. This was the second mission attacking the factories at Schweinfurt. American wartime intelligence claimed the first Schweinfurt–Regensburg mission in August had reduced bearing production by 34% but had suffered heavy losses. A planned follow-up raid had to be postponed to rebuild American forces.
            </p>
			<p>
			As the squadrons rebuilt, plans for the return mission were modified based on the lessons learned. Planners added additional fighter escorts to cover the outward and return legs of the operations, and sent the entire force against Schweinfurt alone, instead of splitting the force. Despite these tactical modifications, a series of minor mishaps combined with the ever-increasing efficiency of the German anti-aircraft efforts proved to be devastating. Of the 291 B-17 Flying Fortresses sent on the mission, 60 were lost outright, another 17 damaged so heavily that they had to be scrapped, and another 121 had varying degrees of battle damage. Outright losses represented over 26% of the attacking force. Losses in aircrew were equally heavy, with 650 men lost of 2,900, 22% of the bomber crews. The American Official History of the Army Air Forces in the Second World War acknowledged losses had been so heavy that the USAAF would not return to the target for four months; "The fact was that the Eighth Air Force had for the time being lost air superiority over Germany".
			</p>
            <p>
			The operation was a failure at all levels. At this time there were no Merlin engined P-51 Mustangs squadrons for long-range escort and the P-47 Thunderbolt was totally inadequate for the job so the bomber formations were left exposed to unrelenting attacks by German fighters; and the improper preparations for the creation of reserves in the summer of 1943 meant that current logistics could not sustain such costly operations. The intelligence of the Allied Air Forces were also flawed. Arthur Harris, Air Officer Commanding RAF Bomber Command questioned the intelligence that claimed ball bearings to be the critical node in the German war economy. Harris refused to cooperate with the Americans, believing ball bearing targets to be a false "panacea". Post-war analysis has shown Harris's objections to be correct. However, an escort of 24 squadrons of Spitfires equipped with drop tanks was provided on the first and last leg of the mission. The Germans had built up enormous reserves of ball bearings and were receiving supplies from all over Europe, particularly Italy, Sweden and Switzerland. The operation against these industries would, even if successful, have achieved little. By 1945 the Germans had assembled more reserves than ever before. 
			</p>
			</div>
			<div>
			<h3> Why the Raid Failed </h3>
			<p>
			The failure of the Schweinfurt Raid was the culmination of years of poor thinking on the part American bomber command. It began with the idea of daylight precision bombing in the first place. Even though their British allies were against it, American commanders insisted on daylight bombing runs. They stated that this would allow them to attack key industrial targets in Germany without major collateral damage. The British on the other hand believed in nighttime area bombing runs. These would attack major cities and attempt to “dehouse and demoralize” the German citizens. Attacking at night also made the bombers safer from the better German fighters of the time. General Ira Eaker, determined to prove the effectiveness of daylight bombing, launched the raid without the help of the British allies as they were wholly against the idea. In the British mind, these raids left too much up to chance and allowed for too high casualties, especially without fighter escorts in tow. .
			</p>
			<p>
			 The second reason for the disaster had to do with the design of the bombers themselves. When heavy bombers began being developed in the last decade before the start of the war, the Army Air Force fully believed that bombers like the B-17, bristling with 12 .50-caliber turrets, could protect itself from any resistance enemy fighters could offer it. This severely delayed the development of any long range escort fighter since they were seen as a waste of time and money for the USAAF. Although the B-17F model, the one in use during the raid, had a dozen guns, it lacked any firepower in the nose of the airplane. This meant that any attack coming directly from the front of the aircraft was indefensible, something the German Luftwaffe fighters took full advantage of during the raid. 
			</p>
			<p>
			The third issue the bombers encountered was the poor intelligence that was given to them before the raid. According to their reports, the majority of German fighter were scattered around the “fighter belt” along the Atlantic Coast of Europe. This put Germany's best fighter planes, the ME 109 and FW 190, well within range of current Allied escort fighters. According to this information, the enemy aircraft they would be facing outside the range of the escorts were heavier two-engine fighters like the ME 110 which were much less maneuverable and easier to shoot down. This turned out to be false as the Germans had moved much of the Luftwaffe deeper into Europe to serve as a defense against the oncoming Russian onslaught in the East. This meant that by the time the escort fighters had to turn around, the bulk of Germany’s fighter planes had just begin to encounter the bombers of the Eighth Air Force. 
			</p>
			<p>
			These factors combined to result in what we now call “Black Thursday” Not only did the Eighth Air Force lose over 20% of the bombers during the raid, the attack on the Schweinfurt factories provided little to no effect on German warmaking capabilities. Becuase of this, all bombing rais deep into Germany were scrapped for the next several months as commanders attempted to learn the lessons that Black thursday attempted to teach them. 
			</p>
			</div>
                
			<div>
			<h3>Changes After the Raid </h3>
			<p>
				It was apparent to the USAAF leadership that long range fighter escort was needed and this would be answered in the upcoming months. In the summer of 1943, America’s aircraft production was focused on bombers first, reconnaissance aircraft second, and “other air force activities” third. The second Schweinfurt raid, October 14th 1943, changed aircraft production priority to fighter production with a focus on the P-38 and the P-47 at the time. Arnold ordered all P-38 and P-47 fighter groups deploying overseas to be sent to Britain but it took time to receive aircraft, train aircrews and emplace the necessary technical support. In the meantime, Major General Ira Eaker sent Eighth Bomber Command out on relatively short missions, within fighter escort range, encountering bad winter weather much of the time instead of the Luftwaffe. But when the Luftwaffe was encountered, the P-38 Lightning had trouble handling the highly maneuverable German fighters due to the Lightning’s turbochargers performing badly at higher altitudes in the high humidity and colder temperatures. The P-38 performed well at lower altitudes in the Mediterranean and Pacific Theaters, but was not suited for colder temperatures found at higher altitudes in north and central Europe. The USAAF leadership pinned hope that the P-38 would be the solution to the long range escort problem but mechanical difficulties blocked that option.
			</p>
			<p>
			A more successful solution to answer the call for increased fighter escort range came in the form of external auxiliary fuel tanks for fighters. As early as 1942, the Eighth AAF inquired whether jettisonable fuel tanks could be made available for the P-47 but the solution was foolishly delayed by the industrial bureaucracy and the lack of emphasis by the USAAF leadership. Meanwhile, local sources in England were tapped to produce a limited quantity of 75 gallon tanks for both the Spitfire and the P-47. Due to the shortage of wartime material in Britain, these 75 gallon tanks were often made of inferior material and had mechanical issues at higher altitudes. By August of 1943, Army Material Command (AMC) was still experimenting at a slow pace with external tanks but had yet to produce its own model. It took a desperate plea by the Eighth’s technical service section chief, Colonel Cass Hough, to get the external fuel tank program kick started. Due to further political pressure applied by the Combined Chiefs, a suitable 150 gallon drop wing tank was quickly developed. In September of 1943, the monthly production of 150 gallon wing tanks for the P-47 was only 300; by December it was 22,000. If the tasking was taken seriously a year earlier, this one innovation could have decreased bomber losses during the fall of 1943 but emphasis arrived too late. As Brigadier General Hume Peabody would put it, the auxiliary tank problem indicated “a lack of forward thinking.” By early 1944, the 150 gallon wing tanks had a significant impact on the fighter escort solution.
			</p>
			<p>
			Also by late fall of 1943, the P-47 received technical upgrades, which included an improved paddle bladed prop and a water injection boost kit, which greatly improved horse power and overall performance. The P-47 could now out-climb its main adversary, the FW-190, and with a new gyro-stabilized gun sight would have a better chance of obtaining hits. The P-47, a seven ton plane equipped with eight fifty caliber machine guns, had its combat range greatly increased by the new 150 gallon droppable wing tanks and performed a majority of the escort missions in early 1944 that swept the Luftwaffe from the skies. Even though the USAAF leadership placed a lot of faith in the P-38 Lightning, it was an entirely new plane that would take center stage for fighter escort duty. The origins of the P-51 are curious enough; in April 1940, the British Air Commission approached North American Aviation for a contract to build Curtis fighters for the RAF. The company suggested an entirely new plane be built and presented the NA-73 Mustang powered by an Allison engine – a prototype completed in only 127 days. The British Air Commission was delighted with the quick turn around and awarded North American with a contract. Before the Japanese attack on Pearl Harbor, 620 Mustangs were shipped to the RAF and made their debut during the Dieppe Raid in the summer of 1942. However, due to the underpowered Allison engine, their performance was not particularly impressive. For this reason, the P-51As were confined to low level tactical missions.
			</p>
			<p>
			In May of 1942, trials were made with five P-51 aircraft outfitted with Rolls Royce Merlin 61 engines in an attempt to improve performance. The results with using these existing components were phenomenal, the P51B (production model) had improved performance at all altitudes especially above 33,000 feet obtaining speeds of 440 m. p. h.. Further adjustments in the controls resulted in improved maneuverability which led to an aircraft equal to or superior, in many aspects, to what the Luftwaffe could offer at the time. North American Aviation received a contract to build the more effective Merlin-61 engine and mate this to its successful airframe in North American’s aircraft manufacturing facilities.
			</p>
			<p>
			By June 1943, 145 P51Bs were shipped to England but served in a reconnaissance role. Sixteen days after the October Schweinfurt raid, Arnold ordered all P-51Bs in England to be withheld from the reconnaissance role, transfer to the fighter escort role, and top priority was given to North American Aviation to produce more Mustangs. The British also agreed that all RAF squadrons, scheduled to convert to P-51 Mustangs, would support Eighth Bomber Command. It was not until the summer of 1944 that P-51s squadrons were ready for combat in numbers so the weight of the spring 1944 air battles fell upon the P-47.
			</p>
			<p>
			When Lieutenant General Jimmy Doolittle took command of the Eighth AAF in December 1943, he made two important changes which at first were unpopular with the heavy bomber crews. First, he increased tours from 25 to 30 missions which upgraded aircrew experience and provided additional cadre for the build-up in new aircrews. Second, despite violent protests from Bomber Command, Doolittle released additional fighters from escort duty to seek out the Luftwaffe whether located in the air or on the ground. Under the old fighter escort system, the fighters would rendezvous with their respective bomber formation to give coverage but the fighters would have to constantly weave, to match the bomber’s speed, and this burned precious fuel. Doolittle’s new system called for relays of fighters to take turns covering the bombers while at the same time taking advantage of each type of fighter’s strength. The Spitfires would escort the bombers from the channel out to 100 miles then the P-47s would take over for the next 150 to 200 miles. Finally, the P-38s would escort the bombers for another 150 to 200 miles. Together, this phased escort system would provide coverage out to 450 miles. As a rule, only one-third of fighters needed to stay near the heavy bombers and escort fighters were rotated in by relays so precious fuel would not be burned by weaving to match the heavy bomber’s speed. The arrival of the P-51B Mustangs in numbers, along with 150 gallon wing tanks, would stretch fighter escort coverage out to 600 miles which was more than enough to reach Berlin. Doolittle’s new escort system was devised to give the bombers maximum coverage while at the same time striking the Luftwaffe where it hurt.
			</p>
			<p>
			Once a fighter group finished its escort task, it could drop down to lower altitudes to strafe enemy airfields. This change in tactics, combined with the increase in Allied fighter escort range, would have a huge impact on the Luftwaffe and disrupt the German practice of rearming and refueling for additional sorties against heavy bombers and eventually account for an irreversible attrition on Luftwaffe pilots. For the first time, Eighth Fighter Command was released to perform their true offensive role.
			</p>
			<p>
			Once the Eighth AAF restarted its daylight strategic bombing campaign in February 1944, Schweinfurt was revisited utilizing a combined bombing strategy. On the night of February 24th, 1944, RAF Bomber Command targeted Schweinfurt. The next morning Eighth Bomber Command, this time escorted by long range fighters, followed up with a daylight raid. Again that night, RAF Bomber Command committed a consecutive night raid that added to a total of 3,000 tons of high explosives onto the Schweinfurt ballbearing facilities. The Combined Bomber Oensive was now better coordinated and could have achieved devastating results. Unfortunately, Sir Arthur Harris, was correct in assuming the Germans dispersed their anti-friction industry by this time as the VFK Works transferred 549 vital machines (from all five factories) to new locations. Thus, the damage from these consecutive raids was not what the Allies hoped.
			</p>
			<p>
			By April 1944, Eighth Fighter Command was ordering new low level fighter sweeps, some in conjunction with bomber missions, deep into Germany. By design, low level fighter sweeps were to catch German aircraft landing, taking off, or on the ground. When heavy or medium bombers were available, the bombers would release ordnance over the German airfields to help neutralize anti-aircraft fire before the fighters strafed. As the spring months wore on, the effects on the Luftwaffe became noticeable as the Luftwaffe was knocked off balance and air superiority turned over to the Allies. At the same time, the German general staff made a serious mistake which threw away any chance of the Luftwaffe regaining air superiority. In face of mounting pressure from the new fighter sweeps, the Germans withdrew their fighters back into Germany in an effort to find a haven and concentrate on Allied bomber formations. By doing so, the Luftwaffe lost its chance to strike Allied escort fighters near the channel and force them to drop their auxiliary tanks early. As it stood the P-47s, and later the P-51s, increased their combat radius further into Germany and soon there was nowhere for the Luftwaffe to hide.
			</p>
			<p>
			The Germans recognized their fall 1943 victory over the Eighth AAF and many on the German general staff believed they stopped the Americans from attacking inside the borders of Germany. Although some Luftwaffe commanders, including General Hubert Weise (who commanded the air defenses of central Germany) were clearly worried, Goring and his staff believed it was impossible for Allied fighters to escort bombers east of Brunswick so they focused their operations on attacking unescorted heavy bombers. Because of this faulty escort range assumption, the Luftwaffe would later be unable to quickly change tactics or equipment (by this time German twin engine fighters were more vulnerable).
			</p>
			</div>
            
			
            <div>
            <h3>About US</h3>
            <p> With this website you will be able to follow the campaigns of the air force during World War 2. Along with the campaigns you will be able to follow a specific crew throughout thier journey though the war. Within each campaign, our algorithms pull the the crews that have had a part to play in the campaign. Also if you see any discrepencies in our work we allow admins to update or delete our work
            </p>
            
                
            </div>
        </div>
	</div>
</div>
